import Link from "next/link";
import { ArrowRight, CalendarClock, CircleAlert, FlaskConical, Target, Zap } from "lucide-react";

export default function HomePage() {
  return <div className="page-wrap dashboard-page">
    <header className="page-header"><div><span className="eyebrow">Saturday, 22 August</span><h1>Good morning</h1><p>Here’s the shortest route to making progress today.</p></div><Link href="/chemistry/ocr-a" className="course-chip"><FlaskConical size={18}/> OCR A Chemistry</Link></header>
    <section className="study-now"><div><span className="recommendation-label"><Zap size={15}/> Recommended next</span><h2>Strengthen atomic structure</h2><p>You’re close to securing 2.1.1. One focused session should clear the remaining weak point before tomorrow’s review.</p><div className="study-meta"><span>12–15 min</span><span>3 mistakes to fix</span><span>78% mastery</span></div><Link href="/chemistry/ocr-a/2-1-1" className="primary-button">Study now <ArrowRight size={17}/></Link></div><div className="study-illustration" aria-hidden="true"><div className="mini-atom"><span></span><i></i><b>+</b></div></div></section>
    <div className="dashboard-grid">
      <section className="dashboard-column"><div className="section-heading"><div><span className="eyebrow">Your course</span><h2>Continue studying</h2></div><Link href="/chemistry/ocr-a">View specification <ArrowRight size={16}/></Link></div><Link href="/chemistry/ocr-a" className="course-card"><div className="course-card-top"><div className="subject-icon"><FlaskConical size={22}/></div><div><strong>OCR A A-Level Chemistry</strong><span>Module 2 · Foundations in chemistry</span></div><span className="progress-percent">62%</span></div><div className="progress-track"><span style={{width:"62%"}}/></div><div className="course-card-bottom"><span>Next: 2.1.1 Atomic structure</span><ArrowRight size={17}/></div></Link></section>
      <aside className="dashboard-side"><div className="mini-card"><CalendarClock size={21}/><div><small>Review due</small><strong>8 cards today</strong><Link href="/flashcards">Start review</Link></div></div><div className="mini-card"><CircleAlert size={21}/><div><small>Weakest area</small><strong>Formulae & equations</strong><Link href="/practice">Fix weaknesses</Link></div></div></aside>
    </div>
    <section><div className="section-heading"><div><span className="eyebrow">Mastery map</span><h2>What’s secure — and what isn’t</h2></div><Link href="/progress">Full progress <ArrowRight size={16}/></Link></div><div className="mastery-preview"><Link href="/chemistry/ocr-a/2-1-1" className="mastery-point good"><span>2.1.1</span><strong>Atomic structure</strong><small>78% · Nearly secure</small></Link><Link href="/chemistry/ocr-a/2-1-2" className="mastery-point medium"><span>2.1.2</span><strong>Formulae & equations</strong><small>44% · Needs work</small></Link><div className="mastery-point low"><span>2.1.3</span><strong>Amount of substance</strong><small>21% · Early stages</small></div><div className="mastery-point empty"><Target size={20}/><strong>Next goal</strong><small>Secure Module 2 foundations</small></div></div></section>
  </div>;
}
