'use client';

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Brain, CircleCheck, FilePenLine, Lightbulb, MessageCircleQuestion, Target, TriangleAlert } from "lucide-react";

type Spec = { code: string; title: string; kicker: string; wording: string; mastery: number; questions: number; mistakes: number; review: string; };
type ContentKey = "atomic" | "equations";
const tabs = ["Learn", "Recall", "Practise", "Exam", "Master"] as const;
type Tab = typeof tabs[number];

export function SpecWorkspace({ spec, contentKey, previous, next }: { spec: Spec; contentKey: ContentKey; previous?: string; next?: string }) {
  const [tab, setTab] = useState<Tab>("Learn");
  return (
    <div className="workspace-page">
      <section className="workspace-main">
        <div className="breadcrumbs"><Link href="/subjects">Subjects</Link><span>›</span><Link href="/chemistry/ocr-a">OCR A Chemistry</Link><span>›</span><span>{spec.code}</span></div>
        <div className="spec-heading-row"><div><span className="eyebrow">{spec.kicker}</span><h1>{spec.code} {spec.title}</h1><p className="lede">Everything you need for this specification point, in one study flow.</p></div><button className="ask-button"><MessageCircleQuestion size={18}/> Ask Avero</button></div>
        <div className="spec-wording"><div className="spec-label">OCR A specification focus</div><p>{spec.wording}</p></div>
        <div className="study-tabs">{tabs.map(t => <button key={t} onClick={() => setTab(t)} className={tab === t ? "study-tab active" : "study-tab"}>{t}</button>)}</div>
        <div className="tab-content">{contentKey === "atomic" ? <AtomicContent tab={tab}/> : <EquationsContent tab={tab}/>}</div>
        <div className="prev-next">{previous ? <Link href={previous} className="secondary-button"><ArrowLeft size={17}/> Previous</Link> : <span/>}{next ? <Link href={next} className="primary-button">Next specification point <ArrowRight size={17}/></Link> : <Link href="/chemistry/ocr-a" className="primary-button">Back to specification <ArrowRight size={17}/></Link>}</div>
      </section>
      <aside className="progress-rail">
        <div className="rail-card mastery-card"><div className="ring" style={{"--progress": `${spec.mastery * 3.6}deg`} as React.CSSProperties}><div><strong>{spec.mastery}%</strong><span>Mastery</span></div></div><p>{spec.mastery >= 70 ? "Nearly secure" : "Building confidence"}</p><small>Your score updates as you study and answer questions.</small></div>
        <div className="rail-card rail-stats"><div><span>Questions completed</span><strong>{spec.questions}</strong></div><div><span>Mistakes to fix</span><strong>{spec.mistakes}</strong></div><div><span>Next review</span><strong>{spec.review}</strong></div></div>
        <Link href="/practice" className="weakness-card"><Target size={21}/><div><strong>Fix my weaknesses</strong><span>Practice the ideas costing you marks.</span></div><ArrowRight size={17}/></Link>
        <div className="rail-card exam-ready"><CircleCheck size={20}/><div><strong>Exam readiness</strong><span>{spec.mastery >= 70 ? "Good — one weak area left" : "Keep going — 3 areas need work"}</span></div></div>
      </aside>
    </div>
  );
}

function AtomicContent({ tab }: { tab: Tab }) {
  if (tab === "Learn") return <>
    <section className="content-card hero-note"><div className="section-icon lavender"><BookOpen size={21}/></div><div><span className="content-kicker">Start here</span><h2>What is actually inside an atom?</h2><p>An atom has a tiny, dense nucleus containing <strong>protons</strong> and <strong>neutrons</strong>. <strong>Electrons</strong> occupy the space around the nucleus. Most of an atom is empty space.</p></div></section>
    <section className="split-content"><div className="content-card"><h3>The three particles</h3><div className="particle-table"><div><strong>Particle</strong><strong>Charge</strong><strong>Relative mass</strong></div><div><span>Proton</span><span>+1</span><span>1</span></div><div><span>Neutron</span><span>0</span><span>1</span></div><div><span>Electron</span><span>−1</span><span>≈ 1/1836</span></div></div></div><div className="content-card atom-visual"><div className="atom-orbit orbit-one"></div><div className="atom-orbit orbit-two"></div><div className="nucleus"><b>p⁺</b><b>n⁰</b></div><span className="electron e1">e⁻</span><span className="electron e2">e⁻</span><span className="visual-caption">Nucleus + surrounding electrons</span></div></section>
    <section className="content-card"><span className="content-kicker">Worked example</span><h2>Reading nuclear notation</h2><div className="worked-example"><div className="nuclide"><sup>23</sup><sub>11</sub>Na<sup>+</sup></div><div className="steps"><p><b>1.</b> Atomic number = 11, so there are <strong>11 protons</strong>.</p><p><b>2.</b> Neutrons = 23 − 11 = <strong>12 neutrons</strong>.</p><p><b>3.</b> Na⁺ has lost one electron, so it has <strong>10 electrons</strong>.</p></div></div></section>
    <section className="content-card tip-card"><Lightbulb size={20}/><div><strong>The thing students mix up</strong><p>Changing the number of electrons makes an <em>ion</em>. Changing the number of neutrons makes an <em>isotope</em>. The number of protons decides which element it is.</p></div></section>
  </>;
  if (tab === "Recall") return <Recall cards={["Atomic number|Number of protons in the nucleus.","Mass number|Total number of protons + neutrons.","Isotope|Atoms of the same element with the same proton number but different neutron numbers.","Ion|A charged particle formed when an atom gains or loses electrons."]}/>;
  if (tab === "Practise") return <QuestionSet title="Quick practice" questions={["For ³⁷₁₇Cl, state the number of protons, neutrons and electrons.","A magnesium ion is ²⁴₁₂Mg²⁺. How many electrons does it contain? Explain your answer.","Explain why two isotopes of chlorine have very similar chemical properties."]}/>;
  if (tab === "Exam") return <ExamQuestion question="An atom of element X contains 17 protons and 20 neutrons. It forms an X⁻ ion. State the mass number of X and the number of electrons in X⁻. Explain why isotopes of X react in the same way. [4 marks]" marks={["Mass number = 37 (1)","X⁻ has 18 electrons (1)","Isotopes have the same electron configuration / same number of outer-shell electrons (1)","Chemical reactions involve electrons, not neutrons (1)"]}/>;
  return <MasterBlock mistakes={["Using relative atomic mass when the question asks for mass number.","Changing proton number when forming an ion.","Saying isotopes have different numbers of electrons instead of neutrons."]} challenge="An ion has 18 electrons, 20 neutrons and a 2+ charge. Identify the element and write its full nuclear notation."/>;
}

function EquationsContent({ tab }: { tab: Tab }) {
  if (tab === "Learn") return <>
    <section className="content-card hero-note"><div className="section-icon mint"><BookOpen size={21}/></div><div><span className="content-kicker">Core idea</span><h2>Equations are chemical bookkeeping</h2><p>A balanced equation must contain the <strong>same number of each type of atom on both sides</strong>. You may change coefficients in front of formulae, but never alter the formula itself just to make an equation balance.</p></div></section>
    <section className="content-card"><h2>Balance it without changing the substances</h2><div className="equation-demo"><span>2Mg</span><b>+</b><span>O₂</span><b>→</b><span>2MgO</span></div><p className="muted">Two magnesium atoms and two oxygen atoms appear on each side. The large 2 is a coefficient; the small ₂ belongs to the formula for oxygen.</p></section>
    <section className="content-card"><span className="content-kicker">Worked example</span><h2>From full equation to ionic equation</h2><div className="steps"><p><b>1.</b> Write the balanced equation: AgNO₃ + NaCl → AgCl + NaNO₃</p><p><b>2.</b> Split aqueous ionic substances into ions.</p><p><b>3.</b> Cancel spectator ions that appear unchanged on both sides.</p><p><b>Answer:</b> Ag⁺(aq) + Cl⁻(aq) → AgCl(s)</p></div></section>
    <section className="content-card tip-card"><TriangleAlert size={20}/><div><strong>Never “fix” a formula to balance an equation</strong><p>H₂O cannot become H₂O₂ just because you need another oxygen. Put a coefficient in front instead.</p></div></section>
  </>;
  if (tab === "Recall") return <Recall cards={["Coefficient|Large number placed before a formula; multiplies the entire formula.","State symbol|(s), (l), (g) or (aq), showing physical state.","Spectator ion|An ion present but unchanged during the reaction.","Ionic equation|An equation showing only the species that actually change."]}/>;
  if (tab === "Practise") return <QuestionSet title="Equation practice" questions={["Balance: Al + O₂ → Al₂O₃","Add state symbols to: NaCl + AgNO₃ → AgCl + NaNO₃ for aqueous reactants.","Write the ionic equation for HCl(aq) reacting with NaOH(aq)."]}/>;
  if (tab === "Exam") return <ExamQuestion question="A student mixes aqueous barium chloride with aqueous sodium sulfate. A white precipitate forms. Write the full balanced equation with state symbols and then the ionic equation. [4 marks]" marks={["BaCl₂ + Na₂SO₄ → BaSO₄ + 2NaCl (1)","Correct state symbols throughout (1)","Ba²⁺(aq) + SO₄²⁻(aq) → BaSO₄(s) (1)","Correct charges and species in ionic equation (1)"]}/>;
  return <MasterBlock mistakes={["Changing subscripts instead of coefficients.","Forgetting to balance charge as well as atoms in ionic equations.","Splitting solids into ions when writing an ionic equation."]} challenge="Write the ionic equation for calcium carbonate reacting with acid, then explain why chloride ions do not appear in it."/>;
}

function Recall({ cards }: { cards: string[] }) { const [open, setOpen] = useState<number | null>(null); return <section><div className="section-title"><div><span className="content-kicker">Recall</span><h2>Can you say it before you reveal it?</h2></div><Brain size={24}/></div><div className="flash-grid">{cards.map((card, i) => { const [front, back] = card.split("|"); return <button className={open === i ? "flash-card revealed" : "flash-card"} key={front} onClick={() => setOpen(open === i ? null : i)}><small>{open === i ? "Answer" : "Tap to reveal"}</small><strong>{open === i ? back : front}</strong></button>})}</div></section>; }
function QuestionSet({ title, questions }: { title: string; questions: string[] }) { return <section><div className="section-title"><div><span className="content-kicker">Practise</span><h2>{title}</h2></div><FilePenLine size={24}/></div><div className="question-list">{questions.map((q,i) => <div className="content-card question" key={q}><span className="q-number">{i+1}</span><div><p>{q}</p><textarea aria-label={`Answer question ${i+1}`} placeholder="Write your answer here…"/></div></div>)}</div><button className="primary-button">Check my answers</button></section>; }
function ExamQuestion({ question, marks }: { question: string; marks: string[] }) { const [show, setShow] = useState(false); return <section><div className="section-title"><div><span className="content-kicker">Exam question</span><h2>Turn knowledge into marks</h2></div><Target size={24}/></div><div className="content-card exam-question"><p>{question}</p><textarea aria-label="Exam answer" placeholder="Write a full exam-style answer…"/><button className="primary-button" onClick={() => setShow(!show)}>{show ? "Hide walkthrough" : "Show mark scheme + walkthrough"}</button></div>{show && <div className="content-card mark-scheme"><h3>Mark-by-mark walkthrough</h3>{marks.map((m,i)=><div className="mark-row" key={m}><span>{i+1}</span><p>{m}</p></div>)}<div className="model-answer"><strong>How to use this</strong><p>Compare each marking point with your own wording. Award a mark only when your answer communicates the scientific idea clearly enough for an examiner to credit it.</p></div></div>}</section>; }
function MasterBlock({ mistakes, challenge }: { mistakes: string[]; challenge: string }) { return <section><div className="section-title"><div><span className="content-kicker">Master</span><h2>Make the marks stick</h2></div><CircleCheck size={24}/></div><div className="split-content"><div className="content-card"><h3>Common mistakes</h3><ul className="mistake-list">{mistakes.map(m=><li key={m}><TriangleAlert size={17}/><span>{m}</span></li>)}</ul></div><div className="content-card challenge-card"><span className="content-kicker">Challenge</span><h3>One level harder</h3><p>{challenge}</p><button className="secondary-button">Attempt challenge</button></div></div><div className="content-card mastery-test"><Target size={22}/><div><h3>Ready for the mastery check?</h3><p>5 short questions. Your result updates this specification point on the mastery map.</p></div><button className="primary-button">Start 5-question check</button></div></section>; }
